### ISSUE TITLE
Panic: concurrent map iteration and map write

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#480]
Happened during tail (after "up"):
```
fatal error: concurrent map iteration and map write

goroutine 1 [running]:
github.com/DefangLabs/defang/src/cmd/cli/command.allInStatus(...)
        /Users/llunesu/dev/defang/src/cmd/cli/command/servicemonitor.go:39
github.com/DefangLabs/defang/src/cmd/cli/command.waitServiceStatus({0x102a040c0, 0x14000127ef0}, {0x101d5a6ca, 0x9}, {0x14000844680, 0x4, 0x0?})
        /Users/llunesu/dev/defang/src/cmd/cli/command/servicemonitor.go:27 +0x1d4
github.com/DefangLabs/defang/src/cmd/cli/command.glob..func12(0x103613840, {0x140000831c0?, 0x0?, 0x4?})
        /Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:842 +0x248
github.com/spf13/cobra.(*Command).execute(0x103613840, {0x14000083180, 0x4, 0x4})
        /Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x103616360)
        /Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/DefangLabs/defang/src/cmd/cli/command.Execute({0x102a040c0?, 0x14000127ef0})
        /Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:64 +0x9c
main.main()
        /Users/llunesu/dev/defang/src/cmd/cli/main.go:27 +0xe8

goroutine 6 [syscall, 4 minutes]:
os/signal.signal_recv()
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/runtime/sigqueue.go:149 +0x2c
os/signal.loop()
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 1
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/os/signal/signal.go:151 +0x28

goroutine 7 [chan receive, 4 minutes]:
main.main.func1()
        /Users/llunesu/dev/defang/src/cmd/cli/main.go:19 +0x30
created by main.main in goroutine 1
        /Users/llunesu/dev/defang/src/cmd/cli/main.go:18 +0xc8

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x1041b6998, 0x72)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x140002f8080?, 0x140004b4000?, 0x0)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x140002f8080, {0x140004b4000, 0x1800, 0x1800})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x140002f8080, {0x140004b4000?, 0x14000583828?, 0x10129040c?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x14000484000, {0x140004b4000?, 0x49?, 0x14b6?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/net.go:179 +0x34
crypto/tls.(*atLeastReader).Read(0x14000454e40, {0x140004b4000?, 0x14000454e40?, 0x0?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/crypto/tls/conn.go:805 +0x40
bytes.(*Buffer).ReadFrom(0x140004882a8, {0x1029e9620, 0x14000454e40})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/bytes/buffer.go:211 +0x90
crypto/tls.(*Conn).readFromUntil(0x14000488000, {0x128ac3fb0?, 0x14000484000}, 0x14c3?)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/crypto/tls/conn.go:827 +0xd0
crypto/tls.(*Conn).readRecordOrCCS(0x14000488000, 0x0)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/crypto/tls/conn.go:625 +0x1e4
crypto/tls.(*Conn).readRecord(...)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0x14000488000, {0x140004e9000, 0x1000, 0x140004d6000?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/crypto/tls/conn.go:1369 +0x168
bufio.(*Reader).Read(0x14000401200, {0x140004ce660, 0x9, 0x30?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/bufio/bufio.go:244 +0x1b4
io.ReadAtLeast({0x1029e7ff8, 0x14000401200}, {0x140004ce660, 0x9, 0x9}, 0x9)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/io/io.go:335 +0xa0
io.ReadFull(...)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/io/io.go:354
net/http.http2readFrameHeader({0x140004ce660, 0x9, 0x438ea0?}, {0x1029e7ff8?, 0x14000401200?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:1635 +0x58
net/http.(*http2Framer).ReadFrame(0x140004ce620)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:1899 +0x78
net/http.(*http2clientConnReadLoop).run(0x14000583f88)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:9339 +0xf8
net/http.(*http2ClientConn).readLoop(0x140004e6000)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:9234 +0x5c
created by net/http.(*http2Transport).newClientConn in goroutine 35
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:7906 +0xabc

goroutine 80 [select, 4 minutes]:
net/http.(*http2clientStream).writeRequest(0x140004e7800, 0x140002eba00)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8549 +0x900
net/http.(*http2clientStream).doRequest(0x14000813290?, 0x140004e4840?)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8411 +0x20
created by net/http.(*http2ClientConn).RoundTrip in goroutine 79
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8317 +0x2d4

goroutine 100 [runnable]:
time.nextStdChunk({0x101d80a94?, 0x6?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/time/format.go:184 +0xe30
time.Time.appendFormat({0x0?, 0x100010000?, 0x103623d00?}, {0x14000615720, 0x0, 0x40}, {0x101d80a7a, 0x20})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/time/format.go:663 +0xf0
time.Time.AppendFormat({0x14000615738?, 0x101d183d8?, 0x103623d00?}, {0x14000615720, 0x0, 0x40}, {0x101d80a7a, 0x20})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/time/format.go:644 +0xf0
time.Time.Format({0x140005be960?, 0xede051141?, 0x103623d00?}, {0x101d80a7a?, 0xede051140?})
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/time/format.go:630 +0xac
github.com/DefangLabs/defang/src/pkg/cli.Tail({0x102a040c0, 0x14000843ea0}, {0x102a147a0, 0x14000490600}, {{0x103658f80, 0x0, 0x0}, {0x140007c8850, 0xc}, {0x24a96dc2, ...}, ...})
        /Users/llunesu/dev/defang/src/pkg/cli/tail.go:305 +0xf94
github.com/DefangLabs/defang/src/cmd/cli/command.startTailing({0x102a040c0, 0x14000843ea0}, {0x140007c8850, 0xc}, {0x0?, 0x0?, 0x103623d00?})
        /Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:793 +0x160
github.com/DefangLabs/defang/src/cmd/cli/command.glob..func12.1()
        /Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:835 +0x70
created by github.com/DefangLabs/defang/src/cmd/cli/command.glob..func12 in goroutine 1
        /Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:832 +0x224

goroutine 102 [select, 4 minutes]:
net/http.(*http2clientStream).writeRequest(0x1400053b500, 0x1400014ef00)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8549 +0x900
net/http.(*http2clientStream).doRequest(0x140007e83f0?, 0x0?)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8411 +0x20
created by net/http.(*http2ClientConn).RoundTrip in goroutine 101
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/net/http/h2_bundle.go:8317 +0x2d4

goroutine 103 [chan send]:
github.com/DefangLabs/defang/src/pkg/cli.Subscribe.func1()
        /Users/llunesu/dev/defang/src/pkg/cli/subscribe.go:63 +0x1b4
created by github.com/DefangLabs/defang/src/pkg/cli.Subscribe in goroutine 1
        /Users/llunesu/dev/defang/src/pkg/cli/subscribe.go:37 +0x350

goroutine 81 [syscall, 4 minutes]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /nix/store/b0rpa34hn6cgbkbn8sfr5dzv723ia3z2-go-1.21.5/share/go/src/runtime/sys_darwin.go:45 +0x68
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /Users/llunesu/go/pkg/mod/golang.org/x/sys@v0.18.0/unix/zsyscall_darwin_arm64.go:275 +0x54
golang.org/x/sys/unix.Kevent(0x0?, {0x140008136c8?, 0x140004ef638?, 0x1013cafd8?}, {0x140004ef678?, 0x0?, 0x140004ef658?}, 0x1013caf70?)
        /Users/llunesu/go/pkg/mod/golang.org/x/sys@v0.18.0/unix/syscall_bsd.go:397 +0x40
github.com/ross96D/cancelreader.(*kqueueCancelReader).wait(0x14000813680)
        /Users/llunesu/go/pkg/mod/github.com/ross96!d/cancelreader@v0.2.6/cancelreader_bsd.go:125 +0x58
github.com/ross96D/cancelreader.(*kqueueCancelReader).Read(0x14000813680, {0x1400065ff28, 0x1, 0x1})
        /Users/llunesu/go/pkg/mod/github.com/ross96!d/cancelreader@v0.2.6/cancelreader_bsd.go:69 +0x44
github.com/DefangLabs/defang/src/pkg/cli.Tail.func1()
        /Users/llunesu/dev/defang/src/pkg/cli/tail.go:201 +0x78
created by github.com/DefangLabs/defang/src/pkg/cli.Tail in goroutine 100
        /Users/llunesu/dev/defang/src/pkg/cli/tail.go:198 +0x560
```

**Comment by lionello** [comment]
Fixed by #481
