### ISSUE TITLE
Panic in compose up

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#881]
## Description:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x103a413c4]

goroutine 1 [running]:
main.main.func1()
	/Users/llunesu/dev/defang/src/cmd/cli/main.go:20 +0x144
panic({0x104103ba0?, 0x1053f6f20?})
	/nix/store/rfcwglhhspqx5v5h0sl4b3py14i6vpxa-go-1.22.7/share/go/src/runtime/panic.go:770 +0x124
github.com/DefangLabs/defang/src/pkg/cli.ComposeUp({0x10474c0a0, 0x1400038cdc0}, {0x10473d898?, 0x140000cc960?}, {0x104759ba8, 0x1400065c1b0}, {0x10475ca28, 0x1400065c180}, 0x0, 0x1)
	/Users/llunesu/dev/defang/src/pkg/cli/composeUp.go:86 +0x2f4
github.com/DefangLabs/defang/src/cmd/cli/command.makeComposeUpCmd.func1(0x14000521b08, {0x140004a5170?, 0x0?, 0x3?})
	/Users/llunesu/dev/defang/src/cmd/cli/command/compose.go:67 +0x1a0
github.com/spf13/cobra.(*Command).execute(0x14000521b08, {0x140004a5110, 0x3, 0x3})
	/Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x105439ee0)
	/Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/llunesu/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/DefangLabs/defang/src/cmd/cli/command.Execute({0x10474c0a0, 0x1400038cdc0})
	/Users/llunesu/dev/defang/src/cmd/cli/command/commands.go:70 +0x9c
main.main()
	/Users/llunesu/dev/defang/src/cmd/cli/main.go:38 +0x10c
```

## Steps to reproduce the problem.

`defang compose up` on playground

## Environment:

- Defang Version (`defang version`):
- Operating system: (e.g., Windows, macOS, Linux)
- Shell (or Browser, if applicable):

**Comment by lionello** [comment]
Could be https://github.com/DefangLabs/defang/pull/880

**Comment by lionello** [comment]
was already fixed
